esphome:
  name: doorbell
  platform: ESP32
  board: esp32cam
wifi:
  ssid: "xxxx"
  password: "xxxx"
  use_address: "192.168.1.103"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: "QnPwLSLEdR2Y"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


  
switch:
  - platform: gpio
    pin: 2
    id: led

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    name: "Doorbell Button"
    on_press:
      then:
      - switch.turn_on: led
    on_release:
      then:
      - switch.turn_off: led



  
# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  reset_pin: GPIO1
  # Image settings
  name: My Camera
  max_framerate: 20fps
  idle_framerate: 1fps
  vertical_flip: true
  horizontal_mirror: true
  # ...

  

  
  
  

  



  
